### ISSUE TITLE
"Optional" is for Java 1.8+ --> Android 24+

### ISSUE THREAD

**Issue by Meisterschueler** [glidernet/ogn-commons-java#4]
The "Optional" Class makes this library unusable for Android < 7.0, so I cannot update the "OGN Viewer" app without loose most users.

**Comment by Meisterschueler** [comment]
I made a branch before Java 8 features were introduced and changed the parser to the 0.2.6 beacons. See Branch "android"

**Comment by wbuczak** [comment]
Hi
Thanks a lot for your feedback. I completely forgot that on android java 8 might not always be available. 
Please be aware that I haven't yet fixed the issue with parsing of the latest receiver beacons format.

**Comment by wbuczak** [comment]
ps. I can't find your branch. Did you push it ?

https://github.com/glidernet/ogn-commons-java/branches

**Comment by Meisterschueler** [comment]
Hi,
my branch is here: https://github.com/Meisterschueler/ogn-commons-java/tree/android
The lastest receiver beacons format will parsed with the android branch because I took the 0.2.6 parsing strings we successfully use in the python and the ruby client (https://github.com/glidernet/python-ogn-client and https://github.com/svoop/ogn_client-ruby)

**Comment by Meisterschueler** [comment]
I cannot push my branch to glidernet because of "permission denied"

**Comment by snip** [comment]
Hi, you need to do  a pull request and owner of the repo will merge it to original.

**Comment by Meisterschueler** [comment]
Okay, I did a pull request.

**Comment by wbuczak** [comment]
Hi again

Thanks for your pull request.  I see that the change is more than just
getting rid of problematic Optional class usage. There are major changes,
such as rework of reg. expressions etc..

Did you test it ?  Does all the test pass ?
Shall I merge it to master branch ?

Cheers
Wojtek

**Comment by wbuczak** [comment]
I've just merged your pull request to the master branch, however the module
fails to build now due to some types incompatibility. Could you please pull
and try to fix the issue ?

Thanks!
Wojtek

$ mvn clean package
[INFO] Scanning for projects...
[INFO]
[INFO]
------------------------------------------------------------------------
[INFO] Building Open Glider Network (OGN) 2.0.0-SNAPSHOT
[INFO]
------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ogn-commons-java
---
[INFO] Deleting D:\glidernet\git\ogn-commons-java\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @
ogn-commons-java ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory
D:\glidernet\git\ogn-commons-java\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.2:compile (default-compile) @
ogn-commons-java ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 33 source files to
D:\glidernet\git\ogn-commons-java\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources)
@ ogn-commons-java ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.2:testCompile (default-testCompile) @
ogn-commons-java ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 18 source files to
D:\glidernet\git\ogn-commons-java\target\test-classes
[INFO] Some messages have been simplified; recompile with -Xdiags:verbose
to get full output
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR]
/D:/glidernet/git/ogn-commons-java/src/test/java/org/ogn/commons/igc/IgcLoggerTest.java:[98,55]
incompatible types: org.ogn.commons.beacon.AircraftDescriptor cannot be
converted to java.util.Optional<org.ogn.commons.beacon.AircraftDescriptor>
[ERROR]
/D:/glidernet/git/ogn-commons-java/src/test/java/org/ogn/commons/igc/IgcLoggerTest.java:[111,55]
incompatible types: org.ogn.commons.beacon.AircraftDescriptor cannot be
converted to java.util.Optional<org.ogn.commons.beacon.AircraftDescriptor>
[ERROR]
/D:/glidernet/git/ogn-commons-java/src/test/java/org/ogn/commons/beacon/impl/aprs/AprsReceiverBeaconTest.java:[121,60]
incompatible types: java.lang.String cannot be converted to
com.google.code.regexp.Matcher
[INFO] 3 errors
[INFO] -------------------------------------------------------------
[INFO]
------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO]
------------------------------------------------------------------------
[INFO] Total time: 3.928 s
[INFO] Finished at: 2017-09-14T12:45:52+02:00
[INFO] Final Memory: 16M/210M
[INFO]
------------------------------------------------------------------------
[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-compiler-plugin:3.6.2:testCompile
(default-testCompile) on project ogn-commons-java: Compilation failure:
Compilation failure:
[ERROR]
/D:/glidernet/git/ogn-commons-java/src/test/java/org/ogn/commons/igc/IgcLoggerTest.java:[98,55]
incompatible types: org.ogn.commons.beacon.AircraftDescriptor cannot be
converted to java.util.Optional<org.ogn.commons.beacon.AircraftDescriptor>
[ERROR]
/D:/glidernet/git/ogn-commons-java/src/test/java/org/ogn/commons/igc/IgcLoggerTest.java:[111,55]
incompatible types: org.ogn.commons.beacon.AircraftDescriptor cannot be
converted to java.util.Optional<org.ogn.commons.beacon.AircraftDescriptor>
[ERROR]
/D:/glidernet/git/ogn-commons-java/src/test/java/org/ogn/commons/beacon/impl/aprs/AprsReceiverBeaconTest.java:[121,60]
incompatible types: java.lang.String cannot be converted to
com.google.code.regexp.Matcher
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e
switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please read the following articles:
[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by Meisterschueler** [comment]
Hi, thank you for merging the pull request. Because you merged the trunk into the branch before you merged the branch into the trunk, now I have all the Java 8 features in the branch. The reason for the branch was to stay away from Java 8, because they make the library nearly unusable for android. So I will again make a branch "android" before you merged the Java 8 features.
Maybe we should think about a library, which is as small and "common" as possible, without Java 8 features or the SMTP software...

**Comment by wbuczak** [comment]
Ups.. let me correct it. I'll revert my changes and will put yours on
android branch

W.

**Comment by Meisterschueler** [comment]
Hi, thank you for the "android" branch. Could you reset the branch to cc641240e8483977bbe967215a24c8b66e012f58? This is the last commit without Java 8 features. Otherwise I assume that I will have problems if I make a pull request.

**Comment by wbuczak** [comment]
Hi!

the android branch should be now reset, as requested.


Wojtek

**Comment by Meisterschueler** [comment]
Thank you, I created pull request #6 for this.
Best regards - Konstantin

**Comment by wbuczak** [comment]
Hi

You should have received an invitation from git-hub to join the
ogn-common-java team. Once you accept I'll grant you the rights to his
repository, so that you can do the merges yourself.

Cheers
W.

**Comment by wbuczak** [comment]
Hi

You should now should be granted sufficient rights to operate on the
ogn-commons-java git repository. Could you please try applying your pull
request yourself in order to test ?

Do you think it would be a good idea to merge some of your improvements
(such as e.g. the rework of the reg. expressions) into the master branch ?

Thanks!
Cheers
Wojtek

**Comment by Meisterschueler** [comment]
Thank you, i just applied the pull request.

I think the different OGN projects should at least use the same regexp for parsing. The regexp in the ruby/python/android library parse the 0.2.6 strings, but it is not so robust. If the APRS string is really corrupt, the regex fails while the "old" ogn regexp can extract the valid parts. And the regexp fails to parse the user comment (my antenna is x, my webcam is y, ...). But with the new 0.2.6 format (APRS status, APRS position, APRS position without comment, APRS message with user comment I did not find any way to make the old regexp work.
So my answer is: yes, good idea, but I do not use the Java 8 trunk and maybe some corrupt messages wont parsed.
